---
title: "CMAM Coverage Dashboard"
author: "University of Liberia School of Public Health Research Team" 
date: "2022-08-28"
output: 
  flexdashboard::flex_dashboard:
    #orientation: rows
    navbar:
      - { title: "Home", href: "cmam_coverage_dashboard.html", align: left }
      - { title: "Urban Montserrado Maps", href: "urban_montserrado_cmam.html", align: left }
      - { title: "Grand Bassa Maps", href: "grand_bassa_cmam.html", align: left }
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(source(here::here("packages.R")))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

## Setup fonts
setup_font(
  id = "open-sans", 
  output_dir = here::here("outputs/fonts"), 
  variants = c("regular", "italic", "700", "700italic"), 
  prefer_local_source = FALSE
)

use_font(
  id = "open-sans", 
  css_path = here::here("outputs/fonts/css/open-sans.css"), 
  selector = ".dummy-selector"
)

# if (!font_family_exists("Open Sans")) {
#   register_font(
#     name = "Open Sans", 
#     plain = list(
#       "outputs/fonts/fonts/open-sans-v34-latin-regular.woff", 0
#     ), 
#     bold = list(
#       "outputs/fonts/fonts/open-sans-v34-latin-700.woff", 0
#     ), 
#     italic = list(
#       "outputs/fonts/fonts/open-sans-v34-latin-italic.woff", 0
#     ),
#     bolditalic = list(
#       "outputs/fonts/fonts/open-sans-v34-latin-700italic.woff", 0
#     )
#   )
# }

targets::tar_load(
  c(
    lbr_counties, lbr_districts, lbr_clans,
    cmam_estimates, cmam_estimates_long, cmam_factors,
    urban_montserrado, grand_bassa,
    urban_montserrado_cmam_coverage, grand_bassa_cmam_coverage
  )
)
```

Column {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Coverage Estimates

```{r urban_montserrado_coverage_estiamtes}
gm_cmam_est <- cmam_estimates_long |>
  subset(survey_area == "Urban Montserrado") |>
  ggplot(
    mapping = aes(
      x = indicators, y = estimate * 100, 
      tooltip = paste0(
        indicators, ": ", 
        round(estimate * 100, digits = 1), "%"
      ), 
      data_id = row.names(
        cmam_estimates_long |> subset(survey_area == "Urban Montserrado")
      )
    )
  ) +
  geom_col_interactive(width = 0.5) +
  scale_y_continuous(limits = c(0, 100)) +
  labs(
    title = "Urban Montserrado",
    x = "", y = "%"
  ) +
  theme_minimal(
    base_family = "sans", base_size = 24
  )


girafe(
  ggobj = gm_cmam_est, width_svg = 11, height_svg = 11,
  options = list(
    opts_sizing(rescale = FALSE),
    opts_tooltip(
      opacity = .7,
      css = "background-color:gray;color:white;padding:2px;border-radius:2px;"
    ),
    opts_hover(css = "fill:#1279BF;stroke:#1279BF;cursor:pointer;")
  )
)
```

### Reasons for non-coverage

```{r urban_montserrado_coverage_factors}
cmam_factors |>
  subset(survey_area == "Urban Montserrado") |>
  ggplot(mapping = aes(x = n, y = reorder(out_reasons, n, decreasing = TRUE))) +
  geom_col() +
  labs(
    title = "Urban Montserrado",
    x = "n", y = ""
  ) +
  theme_minimal()
```

Column {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### Coverage Estimates

```{r grand_bassa_coverage_estiamtes}
gb_cmam_est <- cmam_estimates_long |>
  subset(survey_area == "Grand Bassa") |>
  ggplot(
        mapping = aes(
      x = indicators, y = estimate * 100, 
      tooltip = paste0(
        indicators, ": ", 
        round(estimate * 100, digits = 1), "%"
      ), 
      data_id = row.names(
        cmam_estimates_long |> subset(survey_area == "Grand Bassa")
      )
    )
  ) +
  geom_col_interactive(width = 0.5) +
  scale_y_continuous(limits = c(0, 100)) +
  labs(
    title = "Grand Bassa",
    x = "", y = "%"
  ) +
    theme_minimal(
    base_family = "sans", base_size = 24
  )

girafe(
  ggobj = gb_cmam_est, width_svg = 11, height_svg = 11,
  options = list(
    opts_sizing(rescale = FALSE),
    opts_tooltip(
      opacity = .7,
      css = "background-color:gray;color:white;padding:2px;border-radius:2px;"
    ),
    opts_hover(css = "fill:#1279BF;stroke:#1279BF;cursor:pointer;")
  )
)
```

### Reasons for non-coverage

```{r grand_bassa_coverage_factors}
cmam_factors |>
  subset(survey_area == "Grand Bassa") |>
  ggplot(mapping = aes(x = n, y = reorder(out_reasons, n, decreasing = TRUE))) +
  geom_col() +
  labs(
    title = "Grand Bassa",
    x = "n", y = ""
  ) +
  theme_minimal()
```

<!-- Urban Montserrado -->
<!-- ================================================================================ -->

<!-- Row {.tabset .tabset-fade} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r urban_montserrado_coverage} -->
<!-- pal <- colorNumeric( -->
<!--   palette = brewer.pal(n = 10, name = "RdYlGn"), domain = c(0, 1) -->
<!-- ) -->

<!-- x <- urban_montserrado_cmam_coverage -->

<!-- leaflet(data = x, width = "100%", height = "100%", padding = 0) |> -->
<!--   addMapboxTiles( -->
<!--     style_id = "streets-v10", -->
<!--     username = "mapbox" -->
<!--   ) |> -->
<!--   setView( -->
<!--     lng = mean(st_bbox(urban_montserrado)[c(1, 3)]),  -->
<!--     lat = mean(st_bbox(urban_montserrado)[c(2, 4)]), -->
<!--     zoom = 13 -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(muac_screen), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(muac_screen), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", x$CLNAME,  -->
<!--       "; MUAC screening: ", round(x$muac_screen * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "MUAC Screening" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(oedema_screen), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(oedema_screen), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", x$CLNAME,  -->
<!--       "; Oedema screening: ", round(x$oedema_screen * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Oedema Screening" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(case_finding), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(case_finding), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", x$CLNAME,  -->
<!--       "; Case-finding effectiveness: ", round(x$case_finding * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Case-finding Effectiveness" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(treatment), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(treatment), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", x$CLNAME,  -->
<!--       "; Treatment coverage: ", round(x$treatment * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Treatment Coverage" -->
<!--   ) |> -->
<!--   addCircleMarkers( -->
<!--     data = liberia::settlements, -->
<!--     radius = 5, -->
<!--     fillColor = "blue", -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = "blue", -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     label = paste0( -->
<!--       "Settlement/Village: ", liberia::settlements$FNAME,  -->
<!--       "; County: ", liberia::settlements$admin1Name, -->
<!--       "; District: ", liberia::settlements$admin2Name -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Settlements/Villages" -->
<!--   ) |> -->
<!--   addLegend( -->
<!--     pal = pal, -->
<!--     opacity = 0.7, -->
<!--     values = c(0, 1), -->
<!--     position = "bottomright", -->
<!--     labFormat = labelFormat(suffix = "%", transform = function(x) x * 100), -->
<!--     layerId = "legend" -->
<!--   ) |> -->
<!--   addLayersControl( -->
<!-- 		baseGroups = c("MUAC Screening", "Oedema Screening",  -->
<!-- 		               "Case-finding Effectiveness", "Treatment Coverage"), -->
<!-- 		overlayGroups = c("Settlements/Villages"), -->
<!-- 		position = "topright", -->
<!-- 		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE) -->
<!-- 	) |> -->
<!--   htmlwidgets::onRender(" -->
<!--     function(el, x) { -->
<!--       this.on('baselayerchange', function(e) { -->
<!--         e.layer.bringToBack(); -->
<!--       }) -->
<!--     } -->
<!--   ") -->
<!-- ``` -->


<!-- Grand Bassa -->
<!-- ================================================================================ -->

<!-- Row {.tabset .tabset-fade} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r grand_bassa_coverage} -->
<!-- pal <- colorNumeric( -->
<!--   palette = brewer.pal(n = 10, name = "RdYlGn"), domain = c(0, 1) -->
<!-- ) -->

<!-- y <- grand_bassa_cmam_coverage -->

<!-- leaflet(data = y, width = "100%", height = "100%") |> -->
<!--   addMapboxTiles( -->
<!--     style_id = "streets-v10", -->
<!--     username = "mapbox" -->
<!--   ) |> -->
<!--   setView( -->
<!--     lng = mean(st_bbox(grand_bassa)[c(1, 3)]),  -->
<!--     lat = mean(st_bbox(grand_bassa)[c(2, 4)]), -->
<!--     zoom = 10 -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(muac_screen), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(muac_screen), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", y$CLNAME,  -->
<!--       "; MUAC screening: ", round(y$muac_screen * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "MUAC Screening" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(oedema_screen), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(oedema_screen), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", y$CLNAME,  -->
<!--       "; Oedema screening: ", round(y$oedema_screen * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Oedema Screening" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(case_finding), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(case_finding), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", y$CLNAME,  -->
<!--       "; Case-finding effectiveness: ", round(y$case_finding * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Case-finding Effectiveness" -->
<!--   ) |> -->
<!--   addPolygons( -->
<!--     fillColor = ~pal(treatment), -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = ~pal(treatment), -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     highlight = highlightOptions( -->
<!--       weight = 3, -->
<!--       color = "#666", -->
<!--       dashArray = "", -->
<!--       fillOpacity = 0.7, -->
<!--       bringToFront = TRUE -->
<!--     ), -->
<!--     label = paste0( -->
<!--       "Clan: ", y$CLNAME,  -->
<!--       "; MUAC screening: ", round(y$treatment * 100, digits = 1), "%" -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Treatment Coverage" -->
<!--   ) |> -->
<!--   addCircleMarkers( -->
<!--     data = liberia::settlements, -->
<!--     radius = 3, -->
<!--     fillColor = "blue", -->
<!--     weight = 1, -->
<!--     opacity = 1, -->
<!--     color = "blue", -->
<!--     dashArray = "", -->
<!--     fillOpacity = 0.7, -->
<!--     label = paste0( -->
<!--       "Settlement/Village: ", liberia::settlements$FNAME,  -->
<!--       "; County: ", liberia::settlements$admin1Name, -->
<!--       "; District: ", liberia::settlements$admin2Name -->
<!--     ), -->
<!--     labelOptions = labelOptions( -->
<!--       style = list("font-weight" = "normal", padding = "3px 8px"), -->
<!--       textsize = "12px", -->
<!--       direction = "auto" -->
<!--     ), -->
<!--     group = "Settlements/Villages" -->
<!--   ) |> -->
<!--   addLegend( -->
<!--     pal = pal, -->
<!--     opacity = 0.7, -->
<!--     values = c(0, 1), -->
<!--     position = "bottomright", -->
<!--     labFormat = labelFormat(suffix = "%", transform = function(x) x * 100), -->
<!--     layerId = "legend" -->
<!--   ) |> -->
<!--   addLayersControl( -->
<!-- 		baseGroups = c("MUAC Screening", "Oedema Screening",  -->
<!-- 		               "Case-finding Effectiveness", "Treatment Coverage"), -->
<!-- 		overlayGroups = c("Settlements/Villages"), -->
<!-- 		position = "topright", -->
<!-- 		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE) -->
<!-- 	) |> -->
<!--   htmlwidgets::onRender(" -->
<!--     function(el, x) { -->
<!--       this.on('baselayerchange', function(e) { -->
<!--         e.layer.bringToBack(); -->
<!--       }) -->
<!--     } -->
<!--   ") -->
<!-- ``` -->
