---
title: "Proposed Monitoring and Evaluation Design for the PAI Project"
author: 
date: "019/01/2022"
output: 
  html_document:
    toc: true
    toc_depth: 2
    self_contained: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

suppressPackageStartupMessages(source("packages.R"))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

targets::tar_load(
  c(lbr_counties, lbr_districts, lbr_clans,
    urban_montserrado, grand_bassa, urban_montserrado_ea, grand_bassa_ea,
    urban_montserrado_ea_centroids, grand_bassa_ea_centroids,
    urban_montserrado_sp, grand_bassa_sp,
    urban_montserrado_grid, grand_bassa_grid,
    urban_montserrado_sample, grand_bassa_sample)
)
```

## Urban Montserrado Sample

```{r, echo = FALSE, eval = TRUE, fig.align = "center", fig.width = 10, fig.height = 10}
plot(st_geometry(urban_montserrado), lty = 0)
plot(st_geometry(urban_montserrado_ea), lwd = 0.5, border = "gray50", add = TRUE)
plot(st_geometry(lbr_districts), add = TRUE)
sp::plot(urban_montserrado_sp, pch = 20, cex = 2, col = "red", add = TRUE)
```

```{r, echo = FALSE, eval = TRUE}

```


## Grand Bassa Sample

```{r, echo = FALSE, eval = TRUE, fig.align = "center", fig.width = 10, fig.height = 10}
plot(st_geometry(grand_bassa), lty = 0)
plot(st_geometry(grand_bassa_ea), lwd = 0.5, border = "gray50", add = TRUE)
plot(st_geometry(lbr_counties), add = TRUE)
sp::plot(grand_bassa_sp, pch = 20, cex = 2, col = "red", add = TRUE)
```


