name: monitor survey progress

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: "0 20 * * *"
  workflow_dispatch:
    #branches:
    #  - '*'

jobs:
  monitor-survey-progress:
    runs-on: ubuntu-latest
    container: rocker/geospatial:4.2.0
    env:
      GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          git-crypt libxt6 libglpk-dev

      - name: Trust repo
        run: |
          git config --global --add safe.directory /__w/pai_monitoring_evaluation/pai_monitoring_evaluation
          
      - name: Decrypt repository using symmetric key
        run: |
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -di git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64
          
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@master
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Run daily survey progress review
        run: |
          targets::tar_make(survey_progress_deployed)
        shell: Rscript {0}
          
      - name: Archive daily survey progress review
        run: |
          targets::tar_make(survey_progress_archive_deployed)
        shell: Rscript {0}
        
      - name: Email report
        run: |
          targets::tar_make(progress_report_emailed)
        shell: Rscript {0}
        
      - name: Commit and push files
        run: |
          git config --global user.email "ernest@guevarra.io"
          git config --global user.name "ernestguevarra"
          git add .
          git diff-index --quiet HEAD || git commit -m "deploy survey progress report"
          git push
          